### ISSUE TITLE
Language Names and Glottocodes

### ISSUE THREAD

**Issue by LinguList** [lexibank/walworthpolynesian#9]
@maryewal, could you check the language names in [etc/languages.csv](https://github.com/lexibank/walworthpolynesian/blob/master/etc/languages.csv)? 

I think, the numbers, which we left, are ABVD numbers, which is good, as it means we can trace the languages back to ABVD. This menas: AustralA is 1213, which is [Ra'ivavae](https://abvd.shh.mpg.de/austronesian/language.php?id=1213). So I'd call it Raivavae for the ID, and Ra'ivavae as the "name".

The other languages is [Rurutan](https://abvd.shh.mpg.de/austronesian/language.php?id=128) (ABVD 128).

**Comment by LinguList** [comment]
This means; modifying glottocodes, language names, is all we need, and we are done, I think.

**Comment by LinguList** [comment]
@maryewal, you can now modify all that is in column "Name" and also update glottocodes. The field "NameInSource" should only be left untouched, but this is all of it.

**Comment by maryewal** [comment]
All glottocodes are okay, except Proto Polynesian doesn't seem to have a glottocode any longer...I've left the former one in there just in case it is something incorrect with glottolog search function.

**Comment by LinguList** [comment]
Yes, changing would be very useful!

**Comment by LinguList** [comment]
I just saw: Glottolog has the more specific languages, as descendants of Austral. Maybe we add their glottocodes, to avoid confusion?

**Comment by maryewal** [comment]
You're absolutely right - funny, searching in the main search function doesn't bring it up for me, only in selecting the language do I see the unique codes in the right corner. Thanks!

**Comment by LinguList** [comment]
Yep, this is because Glottolog has this "dialcect" vs. "language" 
distinction, which will only show major languages in the first search 
field. For many varieties this distinction is questionable, but I 
understand the wish to draw a boundary.
